// Senarai semua ID ikon
const iconList = [
  'ableton','activitypub','actix','adonis','ae','aiscript','alpinejs','anaconda','androidstudio',
  'angular','ansible','apollo','apple','appwrite','arch','arduino','astro','atom','au','autocad',
  'aws','azul','azure','babel','bash','bevy','bitbucket','blender','bootstrap','bsd','bun','c','cs',
  'cpp','crystal','cassandra','clion','clojure','cloudflare','cmake','codepen','coffeescript','css',
  'cypress','d3','dart','debian','deno','devto','discord','bots','discordjs','django','docker','dotnet',
  'dynamodb','eclipse','elasticsearch','electron','elixir','elysia','emacs','ember','emotion','express',
  'fastapi','fediverse','figma','firebase','flask','flutter','forth','fortran','gamemakerstudio','gatsby',
  'gcp','git','github','githubactions','gitlab','gmail','gherkin','go','gradle','godot','grafana','graphql',
  'gtk','gulp','haskell','haxe','haxeflixel','heroku','hibernate','html','htmx','idea','ai','instagram',
  'ipfs','java','js','jenkins','jest','jquery','kafka','kali','kotlin','ktor','kubernetes','laravel','latex',
  'less','linkedin','linux','lit','lua','md','mastodon','materialui','matlab','maven','mint','misskey',
  'mongodb','mysql','neovim','nestjs','netlify','nextjs','nginx','nim','nix','nodejs','notion','npm','nuxtjs',
  'obsidian','ocaml','octave','opencv','openshift','openstack','p5js','perl','ps','php','phpstorm','pinia',
  'pkl','plan9','planetscale','pnpm','postgres','postman','powershell','pr','prisma','processing','prometheus',
  'pug','pycharm','py','pytorch','qt','r','rabbitmq','rails','raspberrypi','react','reactivex','redhat',
  'redis','redux','regex','remix','replit','rider','robloxstudio','rocket','rollupjs','ros','ruby','rust',
  'sass','spring','sqlite','stackoverflow','styledcomponents','sublime','supabase','scala','sklearn','selenium',
  'sentry','sequelize','sketchup','solidity','solidjs','svelte','svg','swift','symfony','tailwind','tauri',
  'tensorflow','terraform','threejs','twitter','ts','ubuntu','unity','unreal','v','vala','vercel','vim',
  'visualstudio','vite','vitest','vscode','vscodium','vue','vuetify','wasm','webflow','webpack','webstorm',
  'windicss','windows','wordpress','workers','xd','yarn','yew','zig'
];

// Pemetaan folder dan varian untuk setiap ID ikon
const iconMeta = {
  ae: { folder: 'aftereffects' },
  ai: { folder: 'illustrator' },
  au: { folder: 'audition' },
  ps: { folder: 'photoshop' },
  pr: { folder: 'premiere' },
  cpp: { folder: 'cplusplus' },
  cs: { folder: 'csharp' },
  ts: { folder: 'typescript' },
  js: { folder: 'javascript' },
  md: { folder: 'markdown' },
  py: { folder: 'python' },
  r: { folder: 'r' },
  xd: { folder: 'xd', variant: 'plain' },
  bots: { folder: 'discordbots' },
  discordjs: { folder: 'discordjs' },
  materialui: { folder: 'materialui' },
  sklearn: { folder: 'scikitlearn' },
  windicss: { folder: 'windicss' },
  nuxtjs: { folder: 'nuxtjs' },
  nextjs: { folder: 'nextjs' },
  nestjs: { folder: 'nestjs' },
  nodejs: { folder: 'nodejs' },
  express: { folder: 'express' },
  fastapi: { folder: 'fastapi' },
  flask: { folder: 'flask' },
  django: { folder: 'django' },
  laravel: { folder: 'laravel' },
  rails: { folder: 'rails' },
  symfony: { folder: 'symfony' },
  vue: { folder: 'vuejs' },
  react: { folder: 'react' },
  angular: { folder: 'angular' },
  svelte: { folder: 'svelte' },
  solidjs: { folder: 'solidjs' },
  tailwind: { folder: 'tailwindcss' },
  bootstrap: { folder: 'bootstrap' },
  sass: { folder: 'sass' },
  less: { folder: 'less' },
  jquery: { folder: 'jquery' },
  gulp: { folder: 'gulp' },
  webpack: { folder: 'webpack' },
  rollupjs: { folder: 'rollupjs' },
  vite: { folder: 'vite' },
  vitest: { folder: 'vitest' },
  jest: { folder: 'jest' },
  cypress: { folder: 'cypress' },
  selenium: { folder: 'selenium' },
  postman: { folder: 'postman' },
  docker: { folder: 'docker' },
  kubernetes: { folder: 'kubernetes' },
  terraform: { folder: 'terraform' },
  ansible: { folder: 'ansible' },
  jenkins: { folder: 'jenkins' },
  githubactions: { folder: 'githubactions' },
  gitlab: { folder: 'gitlab' },
  bitbucket: { folder: 'bitbucket' },
  git: { folder: 'git' },
  github: { folder: 'github' },
  aws: { folder: 'amazonwebservices' },
  gcp: { folder: 'googlecloud' },
  azure: { folder: 'azure' },
  firebase: { folder: 'firebase' },
  heroku: { folder: 'heroku' },
  netlify: { folder: 'netlify' },
  vercel: { folder: 'vercel' },
  cloudflare: { folder: 'cloudflare' },
  mongodb: { folder: 'mongodb' },
  postgres: { folder: 'postgresql' },
  mysql: { folder: 'mysql' },
  sqlite: { folder: 'sqlite' },
  redis: { folder: 'redis' },
  elasticsearch: { folder: 'elasticsearch' },
  dynamodb: { folder: 'dynamodb' },
  graphql: { folder: 'graphql' },
  apollo: { folder: 'apollo' },
  prisma: { folder: 'prisma' },
  sequelize: { folder: 'sequelize' },
  hibernate: { folder: 'hibernate' },
  kafka: { folder: 'apachekafka' },
  rabbitmq: { folder: 'rabbitmq' },
  androidstudio: { folder: 'androidstudio' },
  visualstudio: { folder: 'visualstudio' },
  vscode: { folder: 'vscode' },
  idea: { folder: 'intellij' },
  pycharm: { folder: 'pycharm' },
  webstorm: { folder: 'webstorm' },
  phpstorm: { folder: 'phpstorm' },
  clion: { folder: 'clion' },
  rider: { folder: 'rider' },
  eclipse: { folder: 'eclipse' },
  atom: { folder: 'atom' },
  sublime: { folder: 'sublime' },
  emacs: { folder: 'emacs' },
  vim: { folder: 'vim' },
  neovim: { folder: 'neovim' },
  unity: { folder: 'unity' },
  unreal: { folder: 'unrealengine' },
  godot: { folder: 'godot' },
  robloxstudio: { folder: 'robloxstudio' },
  blender: { folder: 'blender' },
  figma: { folder: 'figma' },
  sketchup: { folder: 'sketchup' },
  autocad: { folder: 'autocad' },
  illustrator: { folder: 'illustrator' },
  photoshop: { folder: 'photoshop' },
  premierepro: { folder: 'premierepro' },
  aftereffects: { folder: 'aftereffects' },
  audition: { folder: 'audition' },
  // Varian plain untuk ikon yang tiada varian original
  activitypub: { folder: 'activitypub', variant: 'plain' },
  actix: { folder: 'actix', variant: 'plain' },
  adonis: { folder: 'adonis', variant: 'plain' },
  alpinejs: { folder: 'alpinejs', variant: 'plain' },
  anaconda: { folder: 'anaconda', variant: 'plain' },
  appwrite: { folder: 'appwrite', variant: 'plain' },
  arch: { folder: 'arch', variant: 'plain' },
  arduino: { folder: 'arduino', variant: 'plain' },
  astro: { folder: 'astro', variant: 'plain' },
  azul: { folder: 'azul', variant: 'plain' },
  babel: { folder: 'babel', variant: 'plain' },
  bevy: { folder: 'bevy', variant: 'plain' },
  bsd: { folder: 'bsd', variant: 'plain' },
  bun: { folder: 'bun', variant: 'plain' },
  crystal: { folder: 'crystal', variant: 'plain' },
  cassandra: { folder: 'cassandra', variant: 'plain' },
  clojure: { folder: 'clojure', variant: 'plain' },
  cmake: { folder: 'cmake', variant: 'plain' },
  codepen: { folder: 'codepen', variant: 'plain' },
  coffeescript: { folder: 'coffeescript', variant: 'plain' },
  debian: { folder: 'debian', variant: 'plain' },
  deno: { folder: 'deno', variant: 'plain' },
  devto: { folder: 'devto', variant: 'plain' },
  discord: { folder: 'discord', variant: 'plain' },
  elixir: { folder: 'elixir', variant: 'plain' },
  elysia: { folder: 'elysia', variant: 'plain' },
  ember: { folder: 'ember', variant: 'plain' },
  emotion: { folder: 'emotion', variant: 'plain' },
  fediverse: { folder: 'fediverse', variant: 'plain' },
  flutter: { folder: 'flutter', variant: 'plain' },
  forth: { folder: 'forth', variant: 'plain' },
  fortran: { folder: 'fortran', variant: 'plain' },
  gamemakerstudio: { folder: 'gamemakerstudio', variant: 'plain' },
  gatsby: { folder: 'gatsby', variant: 'plain' },
  gherkin: { folder: 'gherkin', variant: 'plain' },
  go: { folder: 'go', variant: 'plain' },
  gradle: { folder: 'gradle', variant: 'plain' },
  grafana: { folder: 'grafana', variant: 'plain' },
  gtk: { folder: 'gtk', variant: 'plain' },
  haskell: { folder: 'haskell', variant: 'plain' },
  haxe: { folder: 'haxe', variant: 'plain' },
  haxeflixel: { folder: 'haxeflixel', variant: 'plain' },
  htmx: { folder: 'htmx', variant: 'plain' },
  ipfs: { folder: 'ipfs', variant: 'plain' },
  java: { folder: 'java', variant: 'plain' },
  kali: { folder: 'kali', variant: 'plain' },
  kotlin: { folder: 'kotlin', variant: 'plain' },
  ktor: { folder: 'ktor', variant: 'plain' },
  latex: { folder: 'latex', variant: 'plain' },
  linkedin: { folder: 'linkedin', variant: 'plain' },
  lit: { folder: 'lit', variant: 'plain' },
  lua: { folder: 'lua', variant: 'plain' },
  mastodon: { folder: 'mastodon', variant: 'plain' },
  matlab: { folder: 'matlab', variant: 'plain' },
  maven: { folder: 'maven', variant: 'plain' },
  mint: { folder: 'mint', variant: 'plain' },
  misskey: { folder: 'misskey', variant: 'plain' },
  nim: { folder: 'nim', variant: 'plain' },
  nix: { folder: 'nix', variant: 'plain' },
  notion: { folder: 'notion', variant: 'plain' },
  npm: { folder: 'npm', variant: 'plain' },
  obsidian: { folder: 'obsidian', variant: 'plain' },
  ocaml: { folder: 'ocaml', variant: 'plain' },
  octave: { folder: 'octave', variant: 'plain' },
  opencv: { folder: 'opencv', variant: 'plain' },
  openshift: { folder: 'openshift', variant: 'plain' },
  openstack: { folder: 'openstack', variant: 'plain' },
  p5js: { folder: 'p5js', variant: 'plain' },
  perl: { folder: 'perl', variant: 'plain' },
  php: { folder: 'php', variant: 'plain' },
  pinia: { folder: 'pinia', variant: 'plain' },
  pkl: { folder: 'pkl', variant: 'plain' },
  plan9: { folder: 'plan9', variant: 'plain' },
  planetscale: { folder: 'planetscale', variant: 'plain' },
  pnpm: { folder: 'pnpm', variant: 'plain' },
  powershell: { folder: 'powershell', variant: 'plain' },
  processing: { folder: 'processing', variant: 'plain' },
  prometheus: { folder: 'prometheus', variant: 'plain' },
  pug: { folder: 'pug', variant: 'plain' },
  pytorch: { folder: 'pytorch', variant: 'plain' },
  qt: { folder: 'qt', variant: 'plain' },
  reactivex: { folder: 'reactivex', variant: 'plain' },
  redhat: { folder: 'redhat', variant: 'plain' },
  redux: { folder: 'redux', variant: 'plain' },
  regex: { folder: 'regex', variant: 'plain' },
  remix: { folder: 'remix', variant: 'plain' },
  replit: { folder: 'replit', variant: 'plain' },
  rocket: { folder: 'rocket', variant: 'plain' },
  ros: { folder: 'ros', variant: 'plain' },
  ruby: { folder: 'ruby', variant: 'plain' },
  rust: { folder: 'rust', variant: 'plain' },
  spring: { folder: 'spring', variant: 'plain' },
  stackoverflow: { folder: 'stackoverflow', variant: 'plain' },
  styledcomponents: { folder: 'styledcomponents', variant: 'plain' },
  supabase: { folder: 'supabase', variant: 'plain' },
  scala: { folder: 'scala', variant: 'plain' },
  sentry: { folder: 'sentry', variant: 'plain' },
  solidity: { folder: 'solidity', variant: 'plain' },
  svg: { folder: 'svg', variant: 'plain' },
  swift: { folder: 'swift', variant: 'plain' },
  tauri: { folder: 'tauri', variant: 'plain' },
  tensorflow: { folder: 'tensorflow', variant: 'plain' },
  threejs: { folder: 'threejs', variant: 'plain' },
  twitter: { folder: 'twitter', variant: 'plain' },
  ubuntu: { folder: 'ubuntu', variant: 'plain' },
  v: { folder: 'v', variant: 'plain' },
  vala: { folder: 'vala', variant: 'plain' },
  vuetify: { folder: 'vuetify', variant: 'plain' },
  wasm: { folder: 'wasm', variant: 'plain' },
  webflow: { folder: 'webflow', variant: 'plain' },
  windows: { folder: 'windows', variant: 'plain' },
  wordpress: { folder: 'wordpress', variant: 'plain' },
  workers: { folder: 'workers', variant: 'plain' },
  yarn: { folder: 'yarn', variant: 'plain' },
  yew: { folder: 'yew', variant: 'plain' },
  zig: { folder: 'zig', variant: 'plain' }
};
