// ============================================================
//  ICONS.JS – Senarai & Pemetaan Ikon untuk FlashCards Teknologi
//  CDN: Devicon v3 (cdn.jsdelivr.net/gh/devicons/devicon@latest)
// ============================================================

// Senarai lengkap ID ikon (mengikut senarai asal pengguna)
const iconList = [
  'ableton','activitypub','actix','adonis','ae','aiscript','alpinejs','anaconda','androidstudio',
  'angular','ansible','apollo','apple','appwrite','arch','arduino','astro','atom','au','autocad',
  'aws','azul','azure','babel','bash','bevy','bitbucket','blender','bootstrap','bsd','bun','c','cs',
  'cpp','crystal','cassandra','clion','clojure','cloudflare','cmake','codepen','coffeescript','css',
  'cypress','d3','dart','debian','deno','devto','discord','bots','discordjs','django','docker','dotnet',
  'dynamodb','eclipse','elasticsearch','electron','elixir','elysia','emacs','ember','emotion','express',
  'fastapi','fediverse','figma','firebase','flask','flutter','forth','fortran','gamemakerstudio','gatsby',
  'gcp','git','github','githubactions','gitlab','gmail','gherkin','go','gradle','godot','grafana','graphql',
  'gtk','gulp','haskell','haxe','haxeflixel','heroku','hibernate','html','htmx','idea','ai','instagram',
  'ipfs','java','js','jenkins','jest','jquery','kafka','kali','kotlin','ktor','kubernetes','laravel','latex',
  'less','linkedin','linux','lit','lua','md','mastodon','materialui','matlab','maven','mint','misskey',
  'mongodb','mysql','neovim','nestjs','netlify','nextjs','nginx','nim','nix','nodejs','notion','npm','nuxtjs',
  'obsidian','ocaml','octave','opencv','openshift','openstack','p5js','perl','ps','php','phpstorm','pinia',
  'pkl','plan9','planetscale','pnpm','postgres','postman','powershell','pr','prisma','processing','prometheus',
  'pug','pycharm','py','pytorch','qt','r','rabbitmq','rails','raspberrypi','react','reactivex','redhat',
  'redis','redux','regex','remix','replit','rider','robloxstudio','rocket','rollupjs','ros','ruby','rust',
  'sass','spring','sqlite','stackoverflow','styledcomponents','sublime','supabase','scala','sklearn','selenium',
  'sentry','sequelize','sketchup','solidity','solidjs','svelte','svg','swift','symfony','tailwind','tauri',
  'tensorflow','terraform','threejs','twitter','ts','ubuntu','unity','unreal','v','vala','vercel','vim',
  'visualstudio','vite','vitest','vscode','vscodium','vue','vuetify','wasm','webflow','webpack','webstorm',
  'windicss','windows','wordpress','workers','xd','yarn','yew','zig'
];

// ============================================================
//  Pemetaan folder dan varian untuk setiap ID ikon
//  - folder: nama folder dalam repositori devicon
//  - variant: 'original' (default), 'plain', 'plain-wordmark', dsb.
// ============================================================
const iconMeta = {

  // --- ADOBE CREATIVE CLOUD ---
  ae:       { folder: 'aftereffects',   variant: 'original' },
  ai:       { folder: 'illustrator',    variant: 'plain' },
  au:       { folder: 'audition',       variant: 'original' },
  ps:       { folder: 'photoshop',      variant: 'plain' },
  pr:       { folder: 'premiere',       variant: 'original' },
  xd:       { folder: 'xd',             variant: 'plain' },

  // --- BAHASA PENGATURCARAAN ---
  c:        { folder: 'c',              variant: 'plain' },
  cpp:      { folder: 'cplusplus',      variant: 'plain' },
  cs:       { folder: 'csharp',         variant: 'plain' },
  ts:       { folder: 'typescript',     variant: 'original' },
  js:       { folder: 'javascript',     variant: 'original' },
  py:       { folder: 'python',         variant: 'original' },
  r:        { folder: 'r',              variant: 'original' },
  java:     { folder: 'java',           variant: 'original' },
  go:       { folder: 'go',             variant: 'original' },
  rust:     { folder: 'rust',           variant: 'original' },
  ruby:     { folder: 'ruby',           variant: 'original' },
  swift:    { folder: 'swift',          variant: 'original' },
  kotlin:   { folder: 'kotlin',         variant: 'original' },
  scala:    { folder: 'scala',          variant: 'original' },
  perl:     { folder: 'perl',           variant: 'original' },
  php:      { folder: 'php',            variant: 'original' },
  lua:      { folder: 'lua',            variant: 'plain' },
  haskell:  { folder: 'haskell',        variant: 'original' },
  clojure:  { folder: 'clojure',        variant: 'original' },
  elixir:   { folder: 'elixir',         variant: 'original' },
  dart:     { folder: 'dart',           variant: 'original' },
  crystal:  { folder: 'crystal',        variant: 'original' },
  nim:      { folder: 'nim',            variant: 'plain' },
  zig:      { folder: 'zig',            variant: 'plain' },
  v:        { folder: 'v',              variant: 'plain' },
  vala:     { folder: 'vala',           variant: 'original' },
  forth:    { folder: 'forth',          variant: 'plain' },
  fortran:  { folder: 'fortran',        variant: 'original' },
  ocaml:    { folder: 'ocaml',          variant: 'original' },
  octave:   { folder: 'octave',         variant: 'plain' },

  // --- WEB FRAMEWORK & LIBRARY ---
  react:         { folder: 'react',          variant: 'original' },
  angular:       { folder: 'angular',        variant: 'plain' },
  vue:           { folder: 'vuejs',          variant: 'original' },
  svelte:        { folder: 'svelte',         variant: 'original' },
  solidjs:       { folder: 'solidjs',        variant: 'original' },
  nextjs:        { folder: 'nextjs',         variant: 'original' },
  nuxtjs:        { folder: 'nuxtjs',         variant: 'original' },
  nestjs:        { folder: 'nestjs',         variant: 'original' },
  express:       { folder: 'express',        variant: 'original' },
  fastapi:       { folder: 'fastapi',        variant: 'original' },
  flask:         { folder: 'flask',          variant: 'original' },
  django:        { folder: 'django',         variant: 'plain' },
  laravel:       { folder: 'laravel',        variant: 'original' },
  rails:         { folder: 'rails',          variant: 'original' },
  symfony:       { folder: 'symfony',        variant: 'original' },
  spring:        { folder: 'spring',         variant: 'original' },
  bootstrap:     { folder: 'bootstrap',      variant: 'original' },
  tailwind:      { folder: 'tailwindcss',    variant: 'original' },
  sass:          { folder: 'sass',           variant: 'original' },
  less:          { folder: 'less',           variant: 'plain-wordmark' },
  jquery:        { folder: 'jquery',         variant: 'original' },
  alpinejs:      { folder: 'alpinejs',       variant: 'original' },
  htmx:          { folder: 'htmx',           variant: 'original' },
  pug:           { folder: 'pug',            variant: 'plain' },
  emotion:       { folder: 'emotion',        variant: 'original' },
  styledcomponents: { folder: 'styledcomponents', variant: 'original' },

  // --- DATABASE ---
  mongodb:       { folder: 'mongodb',        variant: 'original' },
  postgres:      { folder: 'postgresql',     variant: 'original' },
  mysql:         { folder: 'mysql',          variant: 'original' },
  sqlite:        { folder: 'sqlite',         variant: 'original' },
  redis:         { folder: 'redis',          variant: 'original' },
  elasticsearch: { folder: 'elasticsearch',  variant: 'original' },
  dynamodb:      { folder: 'dynamodb',       variant: 'original' },
  cassandra:     { folder: 'cassandra',      variant: 'original' },
  graphql:       { folder: 'graphql',        variant: 'plain' },
  apollo:        { folder: 'apollo',         variant: 'plain' },
  prisma:        { folder: 'prisma',         variant: 'original' },
  sequelize:     { folder: 'sequelize',      variant: 'original' },
  hibernate:     { folder: 'hibernate',      variant: 'original' },
  planetscale:   { folder: 'planetscale',    variant: 'plain' },

  // --- DEVOPS & CLOUD ---
  docker:        { folder: 'docker',         variant: 'original' },
  kubernetes:    { folder: 'kubernetes',     variant: 'plain' },
  terraform:     { folder: 'terraform',      variant: 'original' },
  ansible:       { folder: 'ansible',        variant: 'original' },
  jenkins:       { folder: 'jenkins',        variant: 'original' },
  githubactions: { folder: 'githubactions',  variant: 'original' },
  gitlab:        { folder: 'gitlab',         variant: 'original' },
  bitbucket:     { folder: 'bitbucket',      variant: 'original' },
  aws:           { folder: 'amazonwebservices', variant: 'original-wordmark' },
  gcp:           { folder: 'googlecloud',    variant: 'original' },
  azure:         { folder: 'azure',          variant: 'original' },
  firebase:      { folder: 'firebase',       variant: 'original' },
  heroku:        { folder: 'heroku',         variant: 'original' },
  netlify:       { folder: 'netlify',        variant: 'original' },
  vercel:        { folder: 'vercel',         variant: 'original' },
  cloudflare:    { folder: 'cloudflare',     variant: 'original' },
  openshift:     { folder: 'openshift',      variant: 'original' },
  openstack:     { folder: 'openstack',      variant: 'original' },
  prometheus:    { folder: 'prometheus',     variant: 'original' },
  grafana:       { folder: 'grafana',        variant: 'original' },
  kafka:         { folder: 'apachekafka',    variant: 'original' },
  rabbitmq:      { folder: 'rabbitmq',       variant: 'original' },
  nginx:         { folder: 'nginx',          variant: 'original' },

  // --- VERSION CONTROL ---
  git:           { folder: 'git',            variant: 'original' },
  github:        { folder: 'github',         variant: 'original' },
  githubactions: { folder: 'githubactions',  variant: 'original' },

  // --- EDITOR & IDE ---
  vscode:        { folder: 'vscode',         variant: 'original' },
  vscodium:      { folder: 'vscodium',       variant: 'original' },
  visualstudio:  { folder: 'visualstudio',   variant: 'plain' },
  idea:          { folder: 'intellij',       variant: 'original' },
  pycharm:       { folder: 'pycharm',        variant: 'original' },
  webstorm:      { folder: 'webstorm',       variant: 'original' },
  phpstorm:      { folder: 'phpstorm',       variant: 'original' },
  clion:         { folder: 'clion',          variant: 'original' },
  rider:         { folder: 'rider',          variant: 'original' },
  eclipse:       { folder: 'eclipse',        variant: 'original' },
  atom:          { folder: 'atom',           variant: 'original' },
  sublime:       { folder: 'sublime',        variant: 'original' },
  emacs:         { folder: 'emacs',          variant: 'original' },
  vim:           { folder: 'vim',            variant: 'original' },
  neovim:        { folder: 'neovim',         variant: 'original' },
  androidstudio: { folder: 'androidstudio',  variant: 'original' },
  autocad:       { folder: 'autocad',        variant: 'original' },
  codepen:       { folder: 'codepen',        variant: 'original' },
  replit:        { folder: 'replit',         variant: 'original' },

  // --- GAME ENGINE ---
  unity:         { folder: 'unity',          variant: 'original' },
  unreal:        { folder: 'unrealengine',   variant: 'original' },
  godot:         { folder: 'godot',          variant: 'original' },
  gamemakerstudio: { folder: 'gamemakerstudio', variant: 'original' },
  robloxstudio:  { folder: 'robloxstudio',   variant: 'original' },

  // --- DESIGN TOOLS ---
  figma:         { folder: 'figma',          variant: 'original' },
  sketchup:      { folder: 'sketchup',       variant: 'original' },
  blender:       { folder: 'blender',        variant: 'original' },

  // --- SISTEM OPERASI & PLATFORM ---
  linux:         { folder: 'linux',          variant: 'original' },
  ubuntu:        { folder: 'ubuntu',         variant: 'plain' },
  debian:        { folder: 'debian',         variant: 'original' },
  arch:          { folder: 'arch',           variant: 'original' },
  kali:          { folder: 'kali',           variant: 'original' },
  windows:       { folder: 'windows',        variant: 'original' },
  apple:         { folder: 'apple',          variant: 'original' },
  android:       { folder: 'android',        variant: 'original' },
  raspberrypi:   { folder: 'raspberrypi',    variant: 'original' },
  bsd:           { folder: 'bsd',            variant: 'original' },
  plan9:         { folder: 'plan9',          variant: 'plain' },

  // --- PENGURUS PAKEJ ---
  npm:           { folder: 'npm',            variant: 'original-wordmark' },
  yarn:          { folder: 'yarn',           variant: 'original' },
  pnpm:          { folder: 'pnpm',           variant: 'original' },
  bun:           { folder: 'bun',            variant: 'original' },
  maven:         { folder: 'maven',          variant: 'original' },
  gradle:        { folder: 'gradle',         variant: 'original' },

  // --- BUNDLER & BUILD TOOLS ---
  webpack:       { folder: 'webpack',        variant: 'original' },
  vite:          { folder: 'vite',           variant: 'original' },
  rollupjs:      { folder: 'rollupjs',       variant: 'original' },
  gulp:          { folder: 'gulp',           variant: 'plain' },
  babel:         { folder: 'babel',          variant: 'original' },

  // --- TESTING ---
  jest:          { folder: 'jest',           variant: 'plain' },
  vitest:        { folder: 'vitest',         variant: 'original' },
  cypress:       { folder: 'cypress',        variant: 'original' },
  selenium:      { folder: 'selenium',       variant: 'original' },

  // --- AI / ML ---
  tensorflow:    { folder: 'tensorflow',     variant: 'original' },
  pytorch:       { folder: 'pytorch',        variant: 'original' },
  opencv:        { folder: 'opencv',         variant: 'original' },
  anaconda:      { folder: 'anaconda',       variant: 'original' },

  // --- MEDIA SOSIAL & KOMUNIKASI ---
  discord:       { folder: 'discord',        variant: 'original' },
  bots:          { folder: 'discordbots',    variant: 'original' },
  discordjs:     { folder: 'discordjs',      variant: 'original' },
  twitter:       { folder: 'twitter',        variant: 'original' },
  instagram:     { folder: 'instagram',      variant: 'original' },
  linkedin:      { folder: 'linkedin',       variant: 'plain' },
  gmail:         { folder: 'gmail',          variant: 'original' },
  mastodon:      { folder: 'mastodon',       variant: 'original' },
  misskey:       { folder: 'misskey',        variant: 'plain' },
  fediverse:     { folder: 'fediverse',      variant: 'plain' },
  devto:         { folder: 'devto',          variant: 'original' },

  // --- LAIN-LAIN ---
  md:            { folder: 'markdown',       variant: 'original' },
  svg:           { folder: 'svg',            variant: 'original' },
  css:           { folder: 'css',            variant: 'original' },
  html:          { folder: 'html',           variant: 'original' },
  bash:          { folder: 'bash',           variant: 'original' },
  powershell:    { folder: 'powershell',     variant: 'original' },
  latex:         { folder: 'latex',          variant: 'original' },
  regex:         { folder: 'regex',          variant: 'original' },
  coffeescript:  { folder: 'coffeescript',   variant: 'original' },
  processing:    { folder: 'processing',     variant: 'original' },
  p5js:          { folder: 'p5js',           variant: 'original' },
  threejs:       { folder: 'threejs',        variant: 'original' },
  d3:            { folder: 'd3',            variant: 'original' },
  electron:      { folder: 'electron',       variant: 'original' },
  tauri:         { folder: 'tauri',          variant: 'original' },
  wasm:          { folder: 'wasm',           variant: 'original' },
  webflow:       { folder: 'webflow',        variant: 'original' },
  wordpress:     { folder: 'wordpress',      variant: 'original' },
  notion:        { folder: 'notion',         variant: 'original' },
  obsidian:      { folder: 'obsidian',       variant: 'original' },
  stackoverflow: { folder: 'stackoverflow',  variant: 'original' },
  rocket:        { folder: 'rocket',         variant: 'plain' },
  postman:       { folder: 'postman',        variant: 'original' },
  materialui:    { folder: 'materialui',     variant: 'original' },
  vuetify:       { folder: 'vuetify',        variant: 'original' },
  windicss:      { folder: 'windicss',       variant: 'original' },
  pinia:         { folder: 'pinia',          variant: 'original' },
  redux:         { folder: 'redux',          variant: 'original' },
  sentry:        { folder: 'sentry',         variant: 'original' },
  solidity:      { folder: 'solidity',       variant: 'original' },
  remix:         { folder: 'remix',          variant: 'original' },
  ros:           { folder: 'ros',            variant: 'original' },
  cmake:         { folder: 'cmake',          variant: 'original' },
  qt:            { folder: 'qt',             variant: 'original' },
  gtk:           { folder: 'gtk',            variant: 'original' },
  lit:           { folder: 'lit',            variant: 'original' },
  bevy:          { folder: 'bevy',           variant: 'original' },
  actix:         { folder: 'actix',          variant: 'original' },
  adonis:        { folder: 'adonis',         variant: 'original' },
  appwrite:      { folder: 'appwrite',       variant: 'original' },
  arduino:       { folder: 'arduino',        variant: 'original' },
  astro:         { folder: 'astro',          variant: 'plain' },
  azul:          { folder: 'azul',           variant: 'original' },
  deno:          { folder: 'deno',           variant: 'original' },
  elysia:        { folder: 'elysia',         variant: 'original' },
  ember:         { folder: 'ember',          variant: 'original' },
  gatsby:        { folder: 'gatsby',         variant: 'original' },
  gherkin:       { folder: 'gherkin',        variant: 'original' },
  haxe:          { folder: 'haxe',           variant: 'original' },
  haxeflixel:    { folder: 'haxeflixel',     variant: 'original' },
  ipfs:          { folder: 'ipfs',           variant: 'original' },
  ktor:          { folder: 'ktor',           variant: 'original' },
  mint:          { folder: 'mint',           variant: 'original' },
  nix:           { folder: 'nix',            variant: 'original' },
  pkl:           { folder: 'pkl',            variant: 'original' },
  reactivex:     { folder: 'reactivex',      variant: 'original' },
  redhat:        { folder: 'redhat',         variant: 'original' },
  sklearn:       { folder: 'scikitlearn',    variant: 'original' },
  supabase:      { folder: 'supabase',       variant: 'original' },
  workers:       { folder: 'workers',        variant: 'original' },
  yew:           { folder: 'yew',            variant: 'original' },
  dotnet:        { folder: 'dotnet',         variant: 'original' },
};
